### ISSUE TITLE
Deploy new Spanish translations

### ISSUE THREAD

**Issue by samreid** [phetsims/decaf#120]
From https://github.com/phetsims/website/issues/997#issuecomment-636115280 we would like to redeploy the following sims:

- [ ] Beta Decay (nuclear physics)
- [ ] Alpha decay (nuclear physics)
- [ ] Radioactive Dating Game (nuclear physics)
- [ ] Photoelectric Effect (photoelectric)
- [ ] Molecular motors (optical-tweezers)
- [ ] Stretching-DNA (optical tweezers)
- [ ] Optical Tweezers and applications (optical-tweezers)
- [ ] Capacitor Lab (capacitor-lab)
- [ ] Lasers (lasers)
- [ ] Fluid Pressure and Flow (fluid-pressure-and-flow)
- [ ] Signal Circuit (signal circuit)

**Comment by KatieWoe** [comment]
I went back and looked at all the legacy translations since Mar 31 when decaf testing started. These are all that came in, so if any others need to be added, here is the info:

Date of Email | Project | Language (_Country) | Submitter's Email | Submitter's Name | Title of Email | SVN Revision Number
-- | -- | -- | -- | -- | -- | --
5/28/20 | nuclear-physics | es | diana.lopeztavares@colorado.edu | Diana Lopez | More Java translations | 75163
5/28/20 | photoelectric | es | diana.lopeztavares@colorado.edu | Diana Lopez | More Java translations | 75165
5/28/20 | optical-tweezers | es | diana.lopeztavares@colorado.edu | Diana Lopez | More Java translations | 75164
5/28/20 | capacitor-lab | es | diana.lopeztavares@colorado.edu | Diana Lopez | More Java translations | 75160
5/28/20 | lasers | es | diana.lopeztavares@colorado.edu | Diana Lopez | More Java translations | 75161
5/28/20 | signal-circuit | es | diana.lopeztavares@colorado.edu | Diana Lopez | More Java translations | 75162
5/20/20 | fluid-pressure-and-flow | es | oliver.nix@colorado.edu | Oliver (forwarding unknown) | Spanish translation of two java and flash sims | 75159
5/20/20 | density-and-buoyancy | es | oliver.nix@colorado.edu | Oliver (forwarding unknown) | Spanish translation of two java and flash sims | 75158
4/30/20 | build-a-molecule | da | martinhendes@gmx.net | Martin Hendes | translation danish build-a-molecule | 75138
4/9/20 | microwaves | ca | jguarque@xtec.cat | JORDI GUARQUE SUGRAÑES | microwaves.jar catalan translation | 75128
4/8/20 | hydrogen-atom | sq | avni.berisha@uni-pr.edu | Assoc. Prof. Avni Berisha | Translation: molecule-polarity in Albanian language | 75126
4/8/20 | molecule-polarity | sq | avni.berisha@uni-pr.edu | Assoc. Prof. Avni Berisha | Translation: molecule-polarity in Albanian language | 75127

**Comment by samreid** [comment]
Here's a checklist that combines the previous 2 comments:

- [ ] nuclear-physics
- [ ] photoelectric
- [ ] optical-tweezers
- [ ] capacitor-lab
- [ ] lasers
- [ ] fluid-pressure-and-flow
- [ ] signal-circuit
- [ ] density-and-buoyancy
- [ ] build-a-molecule
- [ ] microwaves
- [ ] hydrogen-atom
- [ ] molecule-polarity

**Comment by samreid** [comment]
I deployed the changes for Capacitor Lab.  This is the first time using the translation deploy process for CheerpJ.  @DianaTavares can you please check the Capacitor Lab CheerpJ version and make sure it is OK?  If it is OK, then I'll work on the rest.

**Comment by DianaTavares** [comment]
It works very well @samreid, Thanks!!

**Comment by samreid** [comment]
I finished deploying the rest.  @DianaTavares do you mind spot checking a few of them to see if everything went OK?

**Comment by DianaTavares** [comment]
It is perfect, thanks @samreid  and @KatieWoe!
