### ISSUE TITLE
Objects randomly dropped while being moved

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/decaf#69]
<b>Test Device</b>

Windows 10 Laptop

<b>Operating System</b>

Windows 10 1903

<b>Browser</b>

Chrome 80.0.3987.163

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/494

Objects may be randomly dropped while being moved, requiring them to be interacted with again.

<b>Visuals</b>

![2020-04-15DecafFaradayChromeDroppedObj](https://user-images.githubusercontent.com/54685448/79513359-dfb8b180-8000-11ea-80c4-d549b3a3c6fd.gif)

**Comment by samreid** [comment]
@pixelzoom would know for sure, but I believe the object is dropped if it crashes into the compass.

**Comment by pixelzoom** [comment]
The magnet and coil are intended to physically bump into each other.  The drag is not in fact interrupted, but it is behaving oddly (and identically) in both the CheerpJ and Java versions.  It seems to stop dragging, but if you move continue dragging by moving the cursor back inside and outside of the magnet, you'll pick it up again. 

My understanding with decaf is that the goal is not to debug the Java versions, but to make them available "as is".   So since this the behavior in the Java version, I recommend closing this issue as "will not fix"

**Comment by kathy-phet** [comment]
Thanks for the catch. I agree with @pixelzoom here. Marking this as "will not fix" and closing it.
